### ISSUE TITLE
Basic_Bert_Unit_model 训练问题

### ISSUE THREAD

**Issue by BeerTai** [kosugi11037/bert-int#1]
作者您好，在Basic_Bert_Unit_model在训练时存在显存不够的情况(12G)，想问您一下您的训练环境是什么样的,谢谢！

**Comment by kosugi11037** [comment]
您好，感谢您对我们工作的关注！ 我们训练所使用的GPU是Tesla P40，CPU是Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz

**Comment by BeerTai** [comment]
好的！感谢~
