### ISSUE TITLE
Description data是如何提取的

### ISSUE THREAD

**Issue by DBDXRHF** [kosugi11037/bert-int#10]
您好，我想问下一下2016-10-des_dict是如何提取的？我看了https://wiki.dbpedia.org/downloads-2016-10也没找到是如何提取的？

**Comment by kosugi11037** [comment]
您好，感谢您对我们工作的关注！我们是从[https://wiki.dbpedia.org/downloads-2016-10](https://wiki.dbpedia.org/downloads-2016-10)这个链接里Datasets部分的“Long Abstracts”数据集中提取的实体描述信息，您可以预览或下载对应的ttl文件来查看一下

**Comment by DBDXRHF** [comment]
万分感谢！另外我想问一句，关系部分的描述我没找到对应哪里下载（我不确定有没有），请指点。（对DBpedia的数据集属实不熟悉）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kosugi11037"<notifications@github.com&gt;; 
发送时间: 2020年12月22日(星期二) 晚上6:45
收件人: "kosugi11037/bert-int"<bert-int@noreply.github.com&gt;; 
抄送: "任鸿飞"<1140313785@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kosugi11037/bert-int] Description data是如何提取的 (#10)





 
您好，感谢您对我们工作的关注！我们是从https://wiki.dbpedia.org/downloads-2016-10这个链接里Datasets部分的“Long Abstracts”数据集中提取的实体描述信息，您可以预览或下载对应的ttl文件来查看一下

**Comment by kosugi11037** [comment]
我们没有使用关系的描述，关于关系的描述是否存在我暂时也并不是十分清楚...或许您可以在DBpedia内找一下试试？
