### ISSUE TITLE
Why aggregation operation by RBF?

### ISSUE THREAD

**Issue by StuLiu** [kosugi11037/bert-int#12]
Hi! You're work inspired me a lot. I have a question about the feature extraction in the chapter "Neighbor-view Interactions".
    Would you mind tell me the reason for the usage of  RBF function to generate features from maximum similarity vectors, or what inspired you to propose the aggregation method. I spent some time to try other aggregation methods. However, the accuracy was lower than yours.
    Thanks for your reading. Looking forward to your reply!

**Comment by kosugi11037** [comment]
Hi, sorry for the late reply, and thanks for your interest!
Some information retrieval methods use RBF kernel to capture the exact and soft matches between a query and a candidate document, they inspired us a lot. You can read [this paper ](https://arxiv.org/pdf/1706.06613.pdf)if you are interested.
