### ISSUE TITLE
Can you tell me about the description of DWY100k?

### ISSUE THREAD

**Issue by wxl1351641822** [kosugi11037/bert-int#13]
Can you tell me about the description of DWY100k?

**Comment by kosugi11037** [comment]
Thanks for your interest in our work! On DWY100K, we use the basic bert unit to encode entity names (not entity descriptions) to obtain entity embeddings. The entity names can be found on [https://github.com/nju-websoft/MultiKE](https://github.com/nju-websoft/MultiKE)

About entity descriptions, maybe you can find them on the original knowledge graphs. For example, the descriptions of English DBpedia can be downloaded from [http://downloads.dbpedia.org/2016-10/core/long_abstracts_en.ttl.bz2](http://downloads.dbpedia.org/2016-10/core/long_abstracts_en.ttl.bz2). (but I'm not sure if every knowledge graph has entity descriptions)
