### ISSUE TITLE
Attribute-view Interactions的问题

### ISSUE THREAD

**Issue by showerage** [kosugi11037/bert-int#3]
您好，请问在论文这一节中，attribute-value pairs应该怎么理解？attribute和value的embedding分别是如何获取的？

**Comment by kosugi11037** [comment]
您好，感谢您对我们工作的关注！首先关于第一个问题，实体是有属性信息的，这种属性信息记录在属性三元组中，即结构为 (entity, attribute , value)的三元组，比如(Texas, area Total, 696241.0)就是属性三元组的一个实际例子。假设我们已知实体e1的相关属性三元组(e1, a1, v1), (e1, a2, v2), (e1, a3, v3)，那么e1的属性信息，或者说它具有的attribute-value pairs就是集合{(a1, v1), (a2, v2), (a3, v3)};

关于第二个问题，每个value的embedding是将value输入到basic bert unit中得到的(也就是Basic bert unit的mlp输出的向量就是value对应的embedding)，相似的，attribute的embedding是把属性名输入到basic bert unit中得到的

**Comment by showerage** [comment]
大致明白了，感谢回答！这是很棒的工作！

**Comment by kosugi11037** [comment]
谢谢~  如果有问题的话随时欢迎交流~
