### ISSUE TITLE
Upload pre-trained BERT unit models

### ISSUE THREAD

**Issue by LiuYuLOL** [kosugi11037/bert-int#4]
Hi,

Thanks for the great work in KG alignment. As the limited memory of my GPUs and the speed of CPUs, could you upload the pre-trained BERT unit models?

Cheers,
Yu

**Comment by kosugi11037** [comment]
Hi Yu, thanks for your interest! You can download pre-trained basic BERT Unit from this link: https://pan.baidu.com/s/1IaZG6GRuAp-jHPum0ruCTA  (password: kczl ) and extract them into `Save_model/` directory. If you can't download the pre-trained model or have any other questions, please feel free to contact me!

Cheers, 
Xiaobin
