### ISSUE TITLE
What are hardware requirements for training bert-int from scratch with/without cuda?

### ISSUE THREAD

**Issue by KartavyaKothari** [kosugi11037/bert-int#5]
I was trying to train bert-int from scratch and ran out of gpu memory. How much do I need min to work with it.

**Comment by kosugi11037** [comment]
Hi, thanks for your interest in our work! The experiments are conducted on Linux servers equipped with Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz and Tesla P40.

**Comment by KartavyaKothari** [comment]
Thanks for the response, I was running it on a 12GB GPU which must have limited me
