### ISSUE TITLE
Why aren't names considered in the descriptions as part of Mbert input?

### ISSUE THREAD

**Issue by KartavyaKothari** [kosugi11037/bert-int#7]
If I keep the description size to 0 and only consider entity names, ther's still a good performance. Why arent they part of descriptions by default, maybe concatenating name with description would be beneficial?

**Comment by kosugi11037** [comment]
Hi, sorry for late reply.  Entity descriptions often contain entity's name. And entity descriptions are richer in semantic information than entity names. Intuitively, concatenating entity name with entity description as part of model input may have similar effects to only using entity description.
(And I try to use concatenating entity name with entity description as part of model input, the result is really similar.)

**Comment by KartavyaKothari** [comment]
Thanks! got it
