### ISSUE TITLE
Could you share data conversion scripts / rules you used?

### ISSUE THREAD

**Issue by KartavyaKothari** [kosugi11037/bert-int#8]
There is some pre-processing over the DBP15K dataset, could you share the scripts you used to make the data format you have including how you extracted descriptions.

**Comment by kosugi11037** [comment]
About the description file, I extract entity description from [https://wiki.dbpedia.org/downloads-2016-10](https://wiki.dbpedia.org/downloads-2016-10) and remove the parentheses and the string inside the parentheses. (e.g.   "Sven Bender (German pronunciation: [ˈsvɛn ˈbɛndɐ] ; born 27 April 1989) is a German footballer ..." ---> "Sven Bender  is a German footballer ..."    ) 

About DBP15K dataset, you can directly download it from JAPE( [https://github.com/nju-websoft/JAPE](https://github.com/nju-websoft/JAPE) ).

**Comment by KartavyaKothari** [comment]
Okay, thanks a ton for the response :)
If I have some suggestions / doubts could you share an email I could correspond on?

**Comment by kosugi11037** [comment]
My email: txb@ruc.edu.cn
If you have any other questions, please feel free to contact me :)
