### ISSUE TITLE
提供的预训练模型无法正常使用。

### ISSUE THREAD

**Issue by showerage** [kosugi11037/bert-int#9]
您好，根据您在百度网盘中提供的预训练模型无法正常运行。
在运行get_entity_embedding.py 的时候出现了如下报错：
![image](https://user-images.githubusercontent.com/23148749/99782947-c3f82980-2b54-11eb-9072-5bfcf2824c42.png)

**Comment by kosugi11037** [comment]
您好，我想这个问题大概是因为transformers库的版本不同导致的，我实验所使用的版本是2.1.1，我猜您是更高的版本？
您可以和我一样使用2.1.1版本的transformers来运行代码；或者将get_entity_embedding.py中的63行[L63](https://github.com/kosugi11037/bert-int/blob/master/interaction_model/get_entity_embedding.py#L63)中strict设置为False，即改成`Model.load_state_dict(torch.load(bert_model_path, map_location='cpu'),strict=False)` ，这样应该也是可以的
希望这能帮到您，如果上述方法不凑效或者您有其他问题的话，欢迎随时和我联系

**Comment by showerage** [comment]
感谢回答，我切换低对应版本后，成功运行了。想尝试一下DBP15K以外的数据集，请问训练这个BERT模型大概需要多长时间？

**Comment by kosugi11037** [comment]
在DBP15K上，在我们的设备上，印象里basic bert unit部分大概用时是1-2小时左右
